NoteHere/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(1000000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    userId = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    firstName = db.Column(db.String(200))
    lastName = db.Column(db.String(200))
    email = db.Column(db.String(100), unique=True)
    username = db.Column(db.String(20), unique=True)
    password = db.Column(db.String(200))
    notes = db.relationship('Note')

NoteHere/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()

DB_NAME = 'database.db'


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'dasdsad14sferteef154154514f5e15e1f5f11d4f155d151'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note

    createDB(app)

    loginManager = LoginManager()
    loginManager.login_view = 'auth.login'
    loginManager.init_app(app)

    @loginManager.user_loader
    def loadUser(id):
        return User.query.get(int(id))

    return app


def createDB(app):
    if not path.exists('NoteHere/' + DB_NAME):
        db.create_all(app=app)

NoteHere/auth.py
from flask import Blueprint, render_template as rt, url_for, flash, request, redirect
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password):
                flash('Log In successful.', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect Password. Try again', category='error')
        else:
            flash('Email does not exist.', category='error')

    return rt('login.html', title='Log In', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        email1 = User.query.filter_by(email=email).first()
        username1 = User.query.filter_by(username=username).first()

        if email1:
            flash('Email already exist.', category='error')
        elif username1:
            flash('Username already taken.', category='error')
        elif len(firstName) < 1:
            flash('First Name must be greater than 1 character.', category='error')
        elif len(lastName) < 1:
            flash('Last Name must be greater than 1 character.', category='error')
        elif len(email) < 5:
            flash('Email must be greater than 5 characters.', category='error')
        elif len(username) <= 6:
            flash('Username must be at least 6 characters.', category='error')
        elif len(password1) <= 6:
            flash('Password must be at least 6 characters.', category='error')
        elif password1 != password2:
            flash('Confirm Password does not match.', category='error')
        else:
            newuser = User(firstName=firstName, lastName=lastName, email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            db.session.add(newuser)
            db.session.commit()
            flash('Sign Up successful', category='success')
            login_user(newuser, remember=True)
            return redirect(url_for('views.home'))

    return rt('signup.html', title='Sign Up', user=current_user)

NoteHere/views.py
from flask import Blueprint, render_template as rt, url_for, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Note
from . import db
import json

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short.', category='error')
        else:
            newNote = Note(data=note, userId=current_user.id)
            db.session.add(newNote)
            db.session.commit()
            flash('Note added.', category='success')

    return rt('home.html', title='Home', user=current_user)


@views.route('/about')
def about():
    return rt('about.html', title='About', user=current_user)


@views.route('/deleteNote', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.userId == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

NoteHere/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-boddy container">
            <h3 align="center" class="card-title">About</h3>
            <div class="card-subtitle">
                <h6>This web application is created by My self (Shahadath Shahriar) from scratch.</h6>
                <h6>I completed this application using Python library Flask(for backend), Bootstrap5(for frontend).</h6>
            </div>
            <div class="card-text">
                <p>You can visit my projects here,</p>
                <ul>
                    <li><a href="https://github.com/shahadathshahriarakash">GitHub</a></li>
                </ul>
                <p>Cantact Me:</p>
                <ul>
                    <li><a href="https://twitter.com/shahadathshahr2">Twitter</a></li>
                    <li><a href="https://www.instagram.com/shahadathshahr2/">Instagram</a></li>
                </ul>
                <p>More about me?</p>
                <ul>
                    <li><a href="http://shahadathshahr2.bio.link">BioLink</a></li>
                </ul>
                <p>Source file for this Project,</p>
                <ul>
                    <li><a href="https://github.com/shahadathshahriarakash/NoteHere">GitHub</a></li>
                    <li><a href="https://replit.com/@shahadathshahr2/NoteHere">ReplIt</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

NoteHere/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% if title %}
        <title>NoteHere - {{ title }}</title>
    {% else %}
        <title>NoteHere</title>
    {% endif %}

    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('views.home') }}">NoteHere</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% if user.is_authenticated %}
                        <ul class="nav navbar-nav text-center">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('views.home') }}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav ms-auto text-center">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="nav navbar-nav text-center">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav ms-auto text-center">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
                            </li>
                        </ul>
                    {% endif %}

            </div>
        </div>
    </nav>
    <div class="sticky-top mt-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'error' %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% elif category == 'success' %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

NoteHere/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    <div class="row">
      <div class="col-11">{{ note.data }}</div>
      <div class="col-1">
        <button type="button" class="btn-close" aria-label="Close" onClick="deleteNote({{ note.id }})"></button>
      </div>
    </div>

  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form>
{% endblock content %}

NoteHere/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">

          <div class="card-header">
              <h3 align="center">Log In</h3>
          </div>

          <div class="card-body">
            <form method="post" class="mb-3">

              <div class="row">
                  <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" class="form-control" aria-describedby="emailHelp" id="email" name="email" placeholder="Enter Email Address" required>
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                  </div>
              </div>

              <div class="row">
                  <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" required>
                  </div>
              </div>

              <button type="submit" class="btn btn-outline-primary">Log In</button>

            </form>

            <div class="card-text mt-2 border-top pt-3">
              <p>Don't have an account? <a href="{{ url_for('auth.signup') }}" class="ml-2">Sign Up.</a></p>
            </div>

          </div>

    </div>
{% endblock content %}

NoteHere/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">

          <div class="card-header">
              <h3 align="center">Sign Up</h3>
          </div>

          <div class="card-body">
            <form method="post" class="mb-3">

              <div class="row">
                  <div class="mb-3">
                    <label for="firstName" class="form-label">First name*</label>
                    <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First Name">
                  </div>
                  <div class="mb-3">
                    <label for="lastName" class="form-label">Last Name*</label>
                    <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last Name">
                  </div>
              </div>

              <div class="row">
                  <div class="mb-3 col-5">
                    <label for="username" class="form-label">Username*</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="username">
                  </div>
                  <div class="mb-3 col-7">
                    <label for="email" class="form-label">Email address*</label>
                    <input type="email" class="form-control" aria-describedby="emailHelp" id="email" name="email" placeholder="Email Address">
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                  </div>
              </div>

              <div class="row">
                  <div class="mb-3 col-6">
                    <label for="password1" class="form-label">Password*</label>
                    <input type="password" class="form-control" id="password1" name="password1" placeholder="Create Password">
                  </div>
                  <div class="mb-3 col-6">
                    <label for="password2" class="form-label">Confirm Password*</label>
                    <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
                  </div>
              </div>

              <button type="submit" class="btn btn-outline-primary">Sign Up</button>

            </form>

            <div class="card-text mt-2 border-top pt-3">
              <p>Have an account? <a href="{{ url_for('auth.login') }}" class="ml-2">Log In.</a></p>
            </div>

          </div>

    </div>
{% endblock content %}